In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [2]:
path = "Students Images"
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['Arushika.jpeg', 'Shobhit.jpg', 'Vishak.jpg']


In [3]:
for cls in myList:
    curImg = cv2.imread(f'{path}/{cls}')
    images.append(curImg)
    classNames.append(os.path.splitext(cls)[0])
print(classNames)    

['Arushika', 'Shobhit', 'Vishak']


In [4]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList


encodeListKnown = findEncodings(images)

In [5]:
def markAttendance(name):
    with open('Attendance.csv', 'r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')   
            f.writelines(f'\n{name},{dtString}')




In [6]:
cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
    

    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)

    
    for encodeFace, faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)

            markAttendance(name)       

[0.85995882 0.60206672 0.58726502]
VISHAK
[0.72114594 0.40975715 0.55649841]
SHOBHIT
[0.708813   0.40447653 0.52606021]
SHOBHIT
[0.74068826 0.43273749 0.56630681]
SHOBHIT
[0.75410256 0.42315532 0.58508927]
SHOBHIT
[0.73138343 0.41758183 0.56035028]
SHOBHIT
[0.73398898 0.48497722 0.63580619]
SHOBHIT
[0.72803085 0.407179   0.58417834]
SHOBHIT
[0.73419614 0.41765842 0.53460319]
SHOBHIT
[0.77431631 0.44727904 0.58925191]
SHOBHIT
[0.76648212 0.43050676 0.55369637]
SHOBHIT
[0.84143475 0.56835857 0.60702416]
SHOBHIT
[0.76734344 0.42742628 0.56604403]
SHOBHIT
[0.77229249 0.43541377 0.57969144]
SHOBHIT
[0.76645838 0.42035834 0.53293644]
SHOBHIT
[0.778225   0.44349784 0.56798539]
SHOBHIT
[0.75048227 0.42159221 0.56673785]
SHOBHIT


: 

: 